### ISSUE TITLE
Vanilla datacats environment fails to start with AttributeError

### ISSUE THREAD

**Issue by florianm** [datacats/datacats#334] opened 2015-09-30 07:20 UTC
Ok, here's a tricky one. My system should be up to date with:
* apt-get upgraded Ubuntu 14.04 VM
* fresh datacats master install (1.1.0)
* fresh docker install (updated) via `wget -qO- https://get.docker.com/ | sh`
* fresh datacats images via `datacats pull -a`

I've got a handful of existing datacats environments running on that VM which all work fine and can be stopped/restarted. However, creating a new datacats environment, or running `datacats install` inside an existing one will result in a crashing ckan instance.

Live example: 
`datacats create --ckan latest --site-url http://minesweeper.alpha.data.wa.gov.au minesweeper PORT`
creates http://minesweeper.alpha.data.wa.gov.au/ which initially works fine, but as soon as I login (using the admin account created during `datacats create`), it crashes with error trace:

```
Debug at: http://minesweeper.alpha.data.wa.gov.au/_debug/view/1443596557
2015-09-30 07:04:27,533 INFO  [ckan.lib.base]  /images/icons/ckan.ico render time 0.004 seconds
Traceback (most recent call last):
  ...
File "/project/ckan/ckan/model/activity.py", line 298, in dashboard_activity_list
    q = _dashboard_activity_query(user_id, limit + offset)
  File "/project/ckan/ckan/model/activity.py", line 283, in _dashboard_activity_query
    q1 = _user_activity_query(user_id, limit)
  File "/project/ckan/ckan/model/activity.py", line 126, in _user_activity_query
    return _activities_union_all(q1, q2)
  File "/project/ckan/ckan/model/activity.py", line 96, in _activities_union_all
    return model.Session.query(model.Activity).select_entity_from(
AttributeError: 'Query' object has no attribute 'select_entity_from'
```
Hitting /user/logout restores a working CKAN again.

This happens with both `--ckan latest` and `--ckan 2.4`.

If I run `datacats install` in an existing (previously working) environment, datapusher will install https://github.com/okfn/ckan-service-provider/archive/stable.zip which in turn pulls in SQLAlchemy==0.7.8 which in turn collides with latest (vanilla) ckanext-spatial's philosophy on GeoAlchemy2. Strangely, the relevant test in ckanext-spatial which tests for GeoAlchemy versions has been around since well before I ran my last (working) ckan installs.

Where could I have gone wrong? To my knowledge, my datacats installation, docker images, docker installation, and the datacats environment "minesweeper" are vanilla and up to date. 
Any pointers welcome!

update: 
```
(ckan)ubuntu@ip-172-31-22-195:/var/projects/ckan/boom$ datacats shell
Error response from daemon: Cannot start container 5d212a950796f3394e943c6935ec4d5c26097aee1d05298fc51fd26a0c8b270d: Cannot link to a non running container: /datacats_datapusher_boom_primary AS /gloomy_poincare/datapusher
```

`docker ps` confirms that datapusher only runs for the (working) site. So why is datapusher not running on my end? Shouldn't a `datacats reload` also restart the datapusher container?

**Comment by deniszgonjanin** [comment] 2015-09-30 11:53
I'm seeing this as well today. Looking into it

**Comment by deniszgonjanin** [comment] 2015-09-30 12:33
Creating a datacats environment with `datacats create --no-datapusher` works, so it certainly looks like a dependency problem. I'm going to try bringing datapusher up to speed with new requirements and see if that fixes it

**Comment by deniszgonjanin** [comment] 2015-09-30 13:37
Fix depends on this PR https://github.com/ckan/ckan-service-provider/pull/30

Even once that's merged, we would need a new release to be made of ckan-service-provider, and then datapusher will need to be updated. That might take a while...

@JackMc what's the simplest temporary fix here?

**Comment by florianm** [comment] 2015-10-06 07:59
@deniszgonjanin @JackMc sorry for the urgency, but is there any movement yet on this issue?

Alternatively, is there any way to install individual extensions in to a CKAN environment without datapusher? I've tried
```
datacats shell
cd ckanext-myextension
python setup.py install
exit
# outside datacats shell:
added extension to .ini, datacats reload
```
This works except that the extension's resources are not available.
However, running `datacats install` in an pre-datapusher-apocalypse environment with datapusher installed will reliably break and disable that environment.
So, is there a way to `datacats install` without touching datapusher?

**Comment by deniszgonjanin** [comment] 2015-10-06 09:39
Yes, sorry I should have posted the workaround here last week...

Clone [ckan-service-provider](https://github.com/deniszgonjanin/ckan-service-provider) with the fix from above into your datacats environment.

Then do a `datacats install --clean` to clean the *.pyc files and do a fresh install.

**Comment by florianm** [comment] 2015-10-06 12:37
Denis, thanks heaps for the workaround! Will give it a whirl asap!

**Comment by wardi** [comment] 2015-10-06 17:42
It seems like the virtualenv installed by datacats includes sqlalchemy version 0.7.8 not 0.9.6 which is required by the latest ckan. Could this be causing our problems? datacats install --clean would fix the issue because the requirements.txt in ckan has the right sqlalchemy version

**Comment by deniszgonjanin** [comment] 2015-10-06 17:45
@florianm ckan-service-provider 0.0.4 should be right, because I haven't bumped the version. `datacats install --clean` will go through ckan-service-provider and install it and it's dependencies. Once it gets to datapusher, pip detects that ckan-service-provider==0.0.4 is installed, and will not install another one.

If it's not too much hassle, can you confirm that a vanilla `datacats create`/`datacats init` works with the ckan-service-provider fix above? The issue here might have to do with ckanext-spatial specifically. If that's true, let's open a separate issue to track that one

**Comment by florianm** [comment] 2015-10-06 17:53
@wardi I tried `datacats install --clean` multiple times but datapusher is still not starting up.
@deniszgonjanin let me run through my setup step by step just now.

**Comment by wardi** [comment] 2015-10-06 17:54
@florianm thanks, this is a different issue, then

**Comment by florianm** [comment] 2015-10-06 17:56
my error re ckanext-spatial is
```
datacats: problem was encountered:
Error while starting web container:
/project/ckan/ckan/new_authz.py:6: FutureWarning: ckan.new_authz has been renamed to ckan.authz. The ckan.new_authz module will be removed in a future 
release.
  FutureWarning)
2015-10-06 17:35:05,094 DEBUG [ckanext.scheming.plugins] Schema URL is ckanext.scheming:presets.json
2015-10-06 17:35:05,097 DEBUG [ckanext.scheming.plugins] Schema URL is ckanext.datawagovautheme:datawagovau_dataset.json
Traceback (most recent call last):
  File "/usr/lib/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/serve.py", line 284, in command
    relative_to=base, global_conf=vars)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/serve.py", line 321, in loadapp
    **kw)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/deploy/util.py", line 56, in fix_call
    val = callable(*args, **kw)
  File "/project/ckan/ckan/config/middleware.py", line 58, in make_app
    load_environment(conf, app_conf)
  File "/project/ckan/ckan/config/environment.py", line 232, in load_environment
    p.load_all(config)
  File "/project/ckan/ckan/plugins/core.py", line 134, in load_all
    load(*plugins)
  File "/project/ckan/ckan/plugins/core.py", line 166, in load
 plugins_update()
  File "/project/ckan/ckan/plugins/core.py", line 116, in plugins_update
    environment.update_config()
  File "/project/ckan/ckan/config/environment.py", line 403, in update_config
    plugin.configure(config)
  File "/project/ckanext-spatial/ckanext/spatial/plugin.py", line 78, in configure
    setup_model()
  File "/project/ckanext-spatial/ckanext/spatial/model/package_extent.py", line 22, in setup
    define_spatial_tables(srid)
  File "/project/ckanext-spatial/ckanext/spatial/model/package_extent.py", line 69, in define_spatial_tables
    package_extent_table = setup_spatial_table(PackageExtent, db_srid)
  File "/project/ckanext-spatial/ckanext/spatial/geoalchemy_common.py", line 74, in setup_spatial_table
    management=management)),
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 339, in __new__
    "existing Table object." % key)
sqlalchemy.exc.InvalidRequestError: Table 'package_extent' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine o
ptions and columns on an existing Table object.
Starting subprocess with file monitor
```

Seems like a cyclic dependency to me. Never had this one before today.

**Comment by deniszgonjanin** [comment] 2015-10-06 18:08
Haven't ran into this issue before, but I don't use the postgis capabilities of ckanext-spatial much. Is this happening with ckanext-spatial master?

**Comment by florianm** [comment] 2015-10-06 18:15
It's happening with florianm/ckanext-spatial, which is up to date with upstream/master plus my [modifications](https://github.com/ckan/ckanext-spatial/compare/master...florianm:master) for my spatial widget (the one I've pestered you about at scheming). I'm experiencing this error since 4h ago, my fork was fine until just now. The only changes to requirements I've made are an updated version of requests, the other changes are JS/CSS.

**Comment by wardi** [comment] 2015-10-06 18:17
@florianm about four hours ago @JackMc pushed a fix to the docker images, did you do a pull since then?

**Comment by florianm** [comment] 2015-10-06 18:18
twice, but I'm pulling all images again just in case

**Comment by wardi** [comment] 2015-10-06 18:20
@florianm my theory is that fix has caused the new problem you're seeing. Let me see how that can be reverted manually

**Comment by wardi** [comment] 2015-10-06 18:34
I'm really puzzled here, is it possible the module is being imported multiple times with different paths (causing python to think the same module is actually different?) Other than actually having two definitions of package_extent that's all I can think of.

**Comment by florianm** [comment] 2015-10-06 18:40
re datapusher: so, after pulling the latest images, minimal install still has no datapusher:

* datacats create --ckan latest --site-url URL NAME PORT
* docker ps shows: web, solr, db are running (no datapusher)
* git clone https://github.com/deniszgonjanin/ckan-service-provider.git
* vanilla .ini has datapusher plugin enabled
* datacats install --clean
* datacats reload
* docker ps shows: web, solr, db are running (no datapusher)

happy to rebuild my images locally if that's easier! gotta run (gmt+8 here), back in a few hours for more debugging of package_extent.

**Comment by florianm** [comment] 2015-10-06 23:47
Morning everyone, further to the steps above where I tried to setup a datacats ckan _with_ working datapusher, I am getting stuck when I need ckanext-spatial to `datacats paster spatial initdb`, with the command blocking from not finding a running datapusher. This means I'll run into trouble should I populate the ckan with spatially referenced data. I'll retry now above with --no-datapusher.

@wardi @deniszgonjanin @JackMc any pointers re datapusher or updated images/Dockerfiles welcome!

**Comment by JackMc** [comment] 2015-10-06 23:47
@florianm Try another pull, I uploaded new images

**Comment by florianm** [comment] 2015-10-06 23:52
@JackMc forgot to mention, just pulled before my last msg, no luck...

I ran:
* datacats tweak --install-postgis (ok)
* the (failed) datacats paster spatial initdb
* git cloned all my extensions, enabled my extensions in .ini
* datacats reload now fails with:
```
  File "/project/ckanext-spatial/ckanext/spatial/plugin.py", line 78, in configure
    setup_model()
  File "/project/ckanext-spatial/ckanext/spatial/model/package_extent.py", line 22, in setup
    define_spatial_tables(srid)
  File "/project/ckanext-spatial/ckanext/spatial/model/package_extent.py", line 69, in define_spatial_tables
    package_extent_table = setup_spatial_table(PackageExtent, db_srid)
  File "/project/ckanext-spatial/ckanext/spatial/geoalchemy_common.py", line 74, in setup_spatial_table
    management=management)),
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 339, in __new__
    "existing Table object." % key)
sqlalchemy.exc.InvalidRequestError: Table 'package_extent' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
Starting subprocess with file monitor
```

So that means currently there is no way on my end to have a datapusher.
Which changes did you make to the images that could have fixed the datapusher?

**Comment by deniszgonjanin** [comment] 2015-10-07 00:08
@florianm a shitty situation, but in an emergency you can always set up a temporary, standalone datapusher where it's accessible and point your development.ini to it. :hammer:

**Comment by wardi** [comment] 2015-10-07 00:11
@florianm If datapusher is not starting you should be able to run `datacats logs --datapusher` to see the traceback.

**Comment by florianm** [comment] 2015-10-07 00:20
@deniszgonjanin that's genius, I like the percussive maintenance approach :-D would that be "my" .ini or the one in the ~/.datacats data folder where the db passwords are?

@wardi the logs say
```
Traceback (most recent call last):
  File "datapusher/main.py", line 37, in <module>
    main()
  File "datapusher/main.py", line 34, in main
    serve()
  File "datapusher/main.py", line 12, in serve
    web.configure()
AttributeError: 'module' object has no attribute 'configure'
```

Again with -f while I'm datacats reloading (without the spatial ext which throws the cyclic dependency bug):

**Comment by wardi** [comment] 2015-10-07 00:23
the development.ini in the ~/.datacats folder is regenerated from the one in your source directory every time you reload or start, so please edit the one in your source directory :-)

**Comment by JackMc** [comment] 2015-10-07 00:28
https://github.com/JackMc/datacats/tree/334-fix-service-provider Here's the code I've been working on for this... it includes a couple hacks to the docker files, forgive me. :p

**Comment by florianm** [comment] 2015-10-07 00:32
@JackMc I love hacks to Dockerfiles! I can see you've added @deniszgonjanin's ckan-service-provider fork, but is the postgres change related to datapusher?

**Comment by JackMc** [comment] 2015-10-07 00:32
It's not related, but it's required to make our images actually work.

**Comment by JackMc** [comment] 2015-10-07 00:32
Please know that it's destructive and will remove stuff so do it in another VM

**Comment by JackMc** [comment] 2015-10-07 00:33
Like another docker-machine VM

**Comment by florianm** [comment] 2015-10-07 00:44
ayy ok good to know :-D 
questions on your branch for another day (not wanting to hog your time, must be late over there): 
* is it already part of the published images? 
* is it required to build working docker images locally? 
* would this have the same effect as git cloning denis' csp fork and running datacats install --clean? (which does not produce a working datapusher on my end)
* if I use your branch, and build all images, would the datapusher work again/does it work on your end?
I'll have a closer look in a bullet-proof VM later. Thanks for your help!

**Comment by JackMc** [comment] 2015-10-07 00:53
- Yes
- yes
- No
- Doesn't work on my machine, so probably not :-(

**Comment by florianm** [comment] 2015-10-07 00:55
@JackMc awesome! Let me know if you folks have a working datapusher again, until then I'll do without.

Lastest one, can I add datapusher to an env that was created with --no-datapusher? (might be cool to have in docs if there's a path for that)

**Comment by deniszgonjanin** [comment] 2015-10-07 01:10
@florianm yes, just clone datapusher into an environment and `datacats install`

**Comment by florianm** [comment] 2015-10-07 01:21
I'm confused
* isn't datapusher a docker container? 
* Which code could I read to understand how the datapusher container relates to the cloned datapusher repo? 
* From does the environment "know" whether to spin up a datapusher container - the .ini?

**Comment by wardi** [comment] 2015-10-07 01:26
datacats has a bad version of datapusher in the default install version (we're working on a fix, temporary workaround is to clone a new copy of datapusher into your environment source dir)

If a directory called 'datapusher' is present datacats tries to start a datapusher container then expects it to be running. That container is running the datapusher from your environment source directory. datacats should be made more tolerant of a failing datapusher, we've got some tickets open for that.

**Comment by deniszgonjanin** [comment] 2015-10-07 01:31
also, noteworthy is that datapusher simply re-uses the web docker image. The datapusher container is an instance of the web image, simply running a different process. This is similar to all  `datacats shell` or `datacats paster` commands - i.e. celery containers etc...

**Comment by florianm** [comment] 2015-10-07 01:52
@wardi @deniszgonjanin  thanks that was extremely helpful in understanding the workflow!

I take from this:
* I can create a datacats --no-datapusher env, install my extensions, and start using it (if spatial plays ball - I'll find out soon)
* once datacats images are fixed, I can `datacats pull -a` and reload my env to start using the fixed images
* I can add datapusher by cloning a working fork, running `datacats install --clean`, adding `datapusher` to my .ini and reload the env

**Comment by deniszgonjanin** [comment] 2015-10-07 01:59
That all sounds correct, yes :+1:

**Comment by florianm** [comment] 2015-10-07 02:06
thanks! Now I'm getting a clean spatial error again, so latest ckanext-spatial with datacats is not playing nice. Let me dig through the logs and see whom I'll shoot a bug report...

Pasting my error for reference
```
  File "/project/ckanext-spatial/ckanext/spatial/plugin.py", line 78, in configure
    setup_model()
  File "/project/ckanext-spatial/ckanext/spatial/model/package_extent.py", line 22, in setup
    define_spatial_tables(srid)
  File "/project/ckanext-spatial/ckanext/spatial/model/package_extent.py", line 69, in define_spatial_tables
    package_extent_table = setup_spatial_table(PackageExtent, db_srid)
  File "/project/ckanext-spatial/ckanext/spatial/geoalchemy_common.py", line 74, in setup_spatial_table
    management=management)),
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 339, in __new__
    "existing Table object." % key)
sqlalchemy.exc.InvalidRequestError: Table 'package_extent' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
```

with versions
```
$ datacats shell
(ckan)shell@IP:~$ pip freeze | grep lchemy
GeoAlchemy==0.7.2
GeoAlchemy2==0.2.5
SQLAlchemy==0.9.6
kombu-sqlalchemy==1.1.0
sqlalchemy-migrate==0.9.1
```

**Comment by JackMc** [comment] 2015-10-07 02:08
I upgraded the CKAN:2.3 image, can someone make sure it's working?

**Comment by florianm** [comment] 2015-10-09 02:30
Good news everyone: With the latest datacats master and docker images, a vanilla `--latest` ckan install works now with a working datapusher.
There's a remaining issue with ckanext-spatial's SQLAlchemy/GeoAlchemy but that's outside of this issue.
Haven't tested with 2.* yet, but latest looks good to me.
Immensely grateful for resolving this issue within days and providing a workaround in the mean time!

**Comment by wardi** [comment] 2015-10-09 12:03
Glad to hear it!

**Closed by wardi** 2015-10-09 12:03 UTC

**Comment by mchelen** [comment] 2015-12-06 22:09
For anyone who runs into this problem when following the [install guide](http://docs.datacats.com/guide.html) the way to get the latest version which includes the fix for this issue is to change the command:

`datacats create catstown`
to
`datacats create --ckan latest catstown`

**Comment by gamesbook** [comment] 2016-01-07 15:26
Can the install guide be updated?

**Comment by JackMc** [comment] 2016-01-07 15:34
A pull request would be awesome!

**Comment by mchelen** [comment] 2016-01-07 21:50
Can't we change the default image to be 2.4 which has the fix in it?
https://github.com/datacats/datacats/pull/370
That seems better than requiring this workaround.

**Comment by JackMc** [comment] 2016-01-07 21:57
Sounds good. I'll ask Ian then merge that

- Jack

**Comment by Kyle-Falconer** [comment] 2016-05-09 19:02
Running into this issue as well. It happens for me right after trying to log in for the first time.

    AttributeError: 'Query' object has no attribute 'select_entity_from'

I'm also finding that `datacats create --ckan latest catstown` is not enough to prevent the issue, and `datacats logs --datapusher` doesn't return anything.

**Comment by wardi** [comment] 2016-05-09 19:38
is `datacats install --clean` any help? That should grab the right version of sqlalchemy for your ckan

**Comment by Kyle-Falconer** [comment] 2016-05-09 19:49
I did this: 

    datacats install --clean
    datacats run

Then I opened localhost:5281 in firefox, the homepage came up, but when I tried logging in, it came up with the error again.

**Comment by wardi** [comment] 2016-05-10 22:42
I was able to reproduce this. It seems to be related to a datapusher dependency pulling in the wrong version of sqlalchemy. If you don't need datapusher you can remove the datapusher directory and `install --clean` will work

**Comment by wardi** [comment] 2016-05-10 23:00
cloning the latest datapusher also fixes the issue. The datapusher provided with the datacats image must be too old to work with the latest ckan.
