### ISSUE TITLE
Add support for Datapusher

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#9] opened 2015-01-02 20:12 UTC

**Comment by deniszgonjanin** [comment] 2015-05-20 19:08
@wardi @JackMc since you guys are killin' it here, I'd like to bump this issue up.

Related to #52

**Comment by deniszgonjanin** [comment] 2015-05-20 19:10
P.S. there is a lightweight Dockerfile for datapusher here: https://github.com/deniszgonjanin/datapusher/blob/master/Dockerfile

That fork also by default uses tornado instead of the flask process, so it can handle more than 1 request at a time

**Comment by JackMc** [comment] 2015-05-21 18:38
Do you guys think an option to expose a port and/or name the container on "datacats shell" would be a good idea?

**Comment by deniszgonjanin** [comment] 2015-05-21 18:40
Yes, that's what we need essentially. Instead of exposing ports, it would be better if the web and datapusher containers were simply linked the docker way instead

**Comment by deniszgonjanin** [comment] 2015-05-21 18:51
Except, thing to remember is datapusher and web container have a two-way connection, so each needs to be visible to the other. This shouldn't be a problem, except the datapusher container may need an extra host or dns setting to make sure whichever host the web container is running on can be resolved.

All to say, if you implement this, do test that both containers can talk to each other

**Comment by deniszgonjanin** [comment] 2015-06-05 19:29
@JackMc https://github.com/gliderlabs/resolvable

**Comment by JackMc** [comment] 2015-06-05 21:02
So just to write down some of the stuff that we talked about today, here is what we thought is a good way to get this working:

* Datapusher runs in a container called "datacats_{env}_datapusher"
  * This is mounted as a link in the web container.
* The problem is that the site_url in the development linux case is 127.0.0.1. The solution to this will be to set this to the url of the web in the docker bridge interface. This will be done at container run-time. 
* We will use a pre-baked Redis container which is linked to by the datapusher container

Lastly, to formalize the order of booting for the containers:
 1. solr/postgres (doesn't really matter)
 2. redis
 3. datapusher
 4. web (this will rewrite its site_url)

**Comment by JackMc** [comment] 2015-06-08 13:29
@deniszgonjanin It looks like the total size of that container is like 800MB, am I reading wrong?

**Comment by wardi** [comment] 2015-07-24 15:09
fixed in 1.0

**Closed by wardi** 2015-07-24 15:09 UTC
Labels: enhancement, extensions
