### ISSUE TITLE
DB error running create command

### ISSUE THREAD

**Issue by amercader** [datacats/datacats#48] opened 2015-03-22 21:32 UTC
Brand new install, running commands from the [Quickstart](http://docs.datacats.com/quickstart.html) documentation:

```
pip install datacats
datacats pull
datacats create plain
```

I get the following error:

```
(datacats)➜  ckans  datacats create plain
Creating environment "plain"...........Traceback (most recent call last):
  File "/home/adria/dev/pyenvs/datacats/bin/datacats", line 9, in <module>
    load_entry_point('datacats==0.7', 'console_scripts', 'datacats')()
  File "/home/adria/dev/pyenvs/datacats/local/lib/python2.7/site-packages/datacats/cli/main.py", line 116, in main
    return command_fn(opts)
  File "/home/adria/dev/pyenvs/datacats/local/lib/python2.7/site-packages/datacats/cli/create.py", line 40, in create
    ckan_version=opts['--ckan'],
  File "/home/adria/dev/pyenvs/datacats/local/lib/python2.7/site-packages/datacats/cli/create.py", line 72, in create_environment
    fn()
  File "/home/adria/dev/pyenvs/datacats/local/lib/python2.7/site-packages/datacats/project.py", line 418, in ckan_db_init
    db_links=True,
  File "/home/adria/dev/pyenvs/datacats/local/lib/python2.7/site-packages/datacats/project.py", line 735, in run_command
    volumes_from=volumes_from)
  File "/home/adria/dev/pyenvs/datacats/local/lib/python2.7/site-packages/datacats/docker.py", line 101, in web_command
    raise WebCommandError(command, c['Id'][:12])
datacats.docker.WebCommandError: Command failed: /usr/lib/ckan/bin/paster --plugin=ckan db init -c /project/development.ini
  View output: docker logs d0cad23b4672
  Remove stopped container: docker rm d0cad23b4672
```

`docker logs d0cad23b4672` says:

```
sqlalchemy.exc.OperationalError: (OperationalError) could not connect to server: Connection refused
	Is the server running on host "db" (172.17.0.17) and accepting
	TCP/IP connections on port 5432?
 None None
```
I had docker previously installed and the [Docker Hub CKAN image](https://registry.hub.docker.com/u/ckan/ckan/) present, not sure if they may conflict.

(BTW let me know if there's a better channel for support requests like these)

**Comment by wardi** [comment] 2015-03-23 01:10
The images don't conflict. I wonder if your machine is just fast enough to get to that point in the creation before postgres had a chance to start. I should add a loop there to retry a few times.

@amercader would you try moving the line https://github.com/boxkite/datacats/blob/master/datacats/cli/create.py#L59 to below the create_directories line above and let me know if that works?

This is the perfect place for reporting datacats issues.

**Comment by amercader** [comment] 2015-03-25 14:37
I'm afraid that on trying again the error went away, so I can not reproduce it.

After creating a couple of environments I got this other error on running `datacats create`:

```
datacats create spatial22 
Creating environment "spatial22"............
Installing ckan requirements
Installing ckan
Installing ckanext-spatial22theme
Initializing database
Traceback (most recent call last):
  File "/home/adria/dev/pyenvs/datacats/bin/datacats", line 9, in <module>
    load_entry_point('datacats==0.7', 'console_scripts', 'datacats')()
  File "/home/adria/dev/pyenvs/datacats/src/datacats/datacats/cli/main.py", line 116, in main
    return command_fn(opts)
  File "/home/adria/dev/pyenvs/datacats/src/datacats/datacats/cli/create.py", line 40, in create
    ckan_version=opts['--ckan'],
  File "/home/adria/dev/pyenvs/datacats/src/datacats/datacats/cli/create.py", line 76, in create_environment
    return finish_init(project, start_web, create_sysadmin)
  File "/home/adria/dev/pyenvs/datacats/src/datacats/datacats/cli/create.py", line 135, in finish_init
    project.start_web()
  File "/home/adria/dev/pyenvs/datacats/src/datacats/datacats/project.py", line 456, in start_web
    self._run_web_container(port, command)
  File "/home/adria/dev/pyenvs/datacats/src/datacats/datacats/project.py", line 522, in _run_web_container
    5000: port if is_boot2docker() else ('127.0.0.1', port)},
  File "/home/adria/dev/pyenvs/datacats/src/datacats/datacats/docker.py", line 139, in run_container
    port_bindings=port_bindings)
  File "/home/adria/dev/pyenvs/datacats/local/lib/python2.7/site-packages/docker/client.py", line 904, in start
    self._raise_for_status(res)
  File "/home/adria/dev/pyenvs/datacats/local/lib/python2.7/site-packages/docker/client.py", line 119, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Cannot start container 0a4fb176342eac40017b7af8b2926e085eac2546649aa1a82eed38ab55e54bad: Error starting userland proxy: listen tcp 127.0.0.1:5432: bind: address already in use")
```

Doing `datacats purge` and `datacats init` returned the same, but when trying to create a new environment everything worked again (env was created).

If I found them again and can pinpoint the cause I'll let you know.

**Comment by wardi** [comment] 2015-03-25 14:41
That second problem looks like datacats choosing the port your local postgres is already listening on. That's something we're not checking for but should. Would you open a separate issue (it should be reproducible by running `datacats reload <env> 5432`?

**Comment by amercader** [comment] 2015-03-25 14:44
Done: #50

**Comment by wardi** [comment] 2015-03-27 18:35
fixed by #57

**Comment by amercader** [comment] 2015-06-24 14:51
Regarding the first issue described here, I've just tried this on a brand new virtualenv, running datacats 0.11.2, and I can't create any envs. Whenever I run `datacats create xxxx` I get:

```
sqlalchemy.exc.OperationalError: (OperationalError) could not connect to server: Connection refused
	Is the server running on host "db" (172.17.0.93) and accepting
	TCP/IP connections on port 5432?
 None None

```

Full traceback here: https://gist.github.com/amercader/1ee52df928da2abece30

And BTW my laptop is definitely average :)

**Comment by JackMc** [comment] 2015-06-24 15:41
Looking into this no

**Comment by JackMc** [comment] 2015-06-24 15:45
Can you show us the output of ``docker logs datacats_postgres_form1``? It seems your Postgres container is either not running or has been restarted.

**Comment by JackMc** [comment] 2015-06-24 15:46
And also the output of ``docker inspect datacats_postgres_form1``

**Comment by wardi** [comment] 2015-09-25 19:15
closing due to inactivity

**Closed by wardi** 2015-09-25 19:15 UTC
